---
branches:
  - name: main
    protection:
      allow_force_pushes: true
      allow_deletions: false
      required_conversation_resolution: on
      required_linear_history: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - Dependent Issues
          - Semantic Pull Request
          - mergefreeze
          - Run pre-commit checks
